CREATE USER FERME IDENTIFIED BY 'FERMEDUOC';

GRANT CONNECT TO FERME;
GRANT RESOURCE TO FERME;
GRANT CREATE SESSION TO FERME;

ALTER USER FERME DEFAULT TABLESPACE USERS;
ALTER USER FERME TEMPORARY TABLESPACE TEMP;

ALTER USER FERME QUOTA UNLIMITED ON USERS;