# Generated by Django 3.0.6 on 2020-06-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='url_img',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
