# Generated by Django 3.0.6 on 2020-05-28 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(default='NA', max_length=12)),
                ('nombres', models.CharField(default='NA', max_length=50)),
                ('appaterno', models.CharField(default='NA', max_length=50)),
                ('apmaterno', models.CharField(default='NA', max_length=50)),
                ('fecha_nacimiento', models.DateField(default=0)),
                ('genero', models.CharField(default='NA', max_length=6)),
                ('email', models.CharField(default='NA', max_length=50)),
                ('telefono', models.IntegerField(default=0)),
                ('nombre_usuario', models.CharField(default='NA', max_length=40)),
                ('contrasena', models.CharField(default='NA', max_length=50)),
                ('cod_admin', models.CharField(default='NA', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(default='NA', max_length=12)),
                ('nombres', models.CharField(default='NA', max_length=50)),
                ('appaterno', models.CharField(default='NA', max_length=50)),
                ('apmaterno', models.CharField(default='NA', max_length=50)),
                ('fecha_nacimiento', models.DateField(default=0)),
                ('genero', models.CharField(default='NA', max_length=6)),
                ('email', models.CharField(default='NA', max_length=50)),
                ('telefono', models.IntegerField(default=0)),
                ('nombre_usuario', models.CharField(default='NA', max_length=40)),
                ('contrasena', models.CharField(default='NA', max_length=50)),
                ('cod_vendedor', models.CharField(default='NA', max_length=6)),
                ('sucursal', models.CharField(default='NA', max_length=55)),
                ('fecha_contrato', models.DateField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apmaterno',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='appaterno',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(default='NA', max_length=6),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_usuario',
            field=models.CharField(default='NA', max_length=40),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='run',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compra',
            name='cliente_usuario_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Cliente'),
        ),
        migrations.AddField(
            model_name='compra',
            name='monto_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='apmaterno',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='appaterno',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='area',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cod_empleado',
            field=models.CharField(default='NA', max_length=6),
        ),
        migrations.AddField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='email',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_contrato',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(default='NA', max_length=6),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombre_usuario',
            field=models.CharField(default='NA', max_length=40),
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombres',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='empleado',
            name='run',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.CharField(default='NA', max_length=55),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_hora',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='usuario',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='anulada',
            field=models.CharField(default='NA', max_length=1),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='compra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Compra'),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='comuna',
            field=models.CharField(default='NA', max_length=45),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='direccion',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='fecha_compra',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='rut_persona',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='sucursal',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='terminal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='tipo_pago',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carro',
            name='carro_id',
            field=models.CharField(default='NA', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Cliente'),
        ),
        migrations.AlterField(
            model_name='carroproducto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carroproducto',
            name='carro',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Carro'),
        ),
        migrations.AlterField(
            model_name='carroproducto',
            name='producto',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.Producto'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Categoria'),
        ),
        migrations.AlterField(
            model_name='categoriaproducto',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto'),
        ),
        migrations.AlterField(
            model_name='despachodomicilio',
            name='compra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Compra'),
        ),
        migrations.AlterField(
            model_name='despachodomicilio',
            name='comuna',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='despachodomicilio',
            name='descripcion',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='despachodomicilio',
            name='direccion',
            field=models.CharField(default='NA', max_length=60),
        ),
        migrations.AlterField(
            model_name='despachodomicilio',
            name='estado',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='despachodomicilio',
            name='fecha_entrega',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='despachodomicilio',
            name='rut_receptor',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AlterField(
            model_name='despachodomicilio',
            name='telefono_contacto',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='anulada',
            field=models.CharField(default='NA', max_length=1),
        ),
        migrations.AlterField(
            model_name='factura',
            name='compra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Compra'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='comuna',
            field=models.CharField(default='NA', max_length=45),
        ),
        migrations.AlterField(
            model_name='factura',
            name='direccion',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_compra',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='rut_empresa',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AlterField(
            model_name='factura',
            name='sucursal',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='factura',
            name='terminal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipo_pago',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='anulada',
            field=models.CharField(default='NA', max_length=1),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='compra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Compra'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='comuna',
            field=models.CharField(default='NA', max_length=45),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='desc_motivo',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='direccion',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='doc_asociado',
            field=models.CharField(default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Empleado'),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='fecha_anulacion',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='fecha_compra',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='sucursal',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='terminal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notacredito',
            name='tipo_pago',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='estado',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='fecha_recepcion',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='proveedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Proveedor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponibilidad',
            field=models.CharField(default='NA', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tienda.Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_normal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_oferta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_critico',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productooc',
            name='orden_de_compra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.OrdenDeCompra'),
        ),
        migrations.AlterField(
            model_name='productooc',
            name='producto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(default='NA', max_length=55),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(default='NA', max_length=55),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fono',
            field=models.CharField(default='NA', max_length=55),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(default='NA', max_length=55),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='sector_comercial',
            field=models.CharField(default='NA', max_length=55),
        ),
        migrations.AlterField(
            model_name='retirotienda',
            name='compra',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Compra'),
        ),
        migrations.AlterField(
            model_name='retirotienda',
            name='empleado',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Empleado'),
        ),
        migrations.AlterField(
            model_name='retirotienda',
            name='estado',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='retirotienda',
            name='fecha_entrega',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='retirotienda',
            name='rut_receptor',
            field=models.CharField(default='NA', max_length=12),
        ),
        migrations.AlterField(
            model_name='retirotienda',
            name='sucursal',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='compra',
            name='vendedor_cod_vendedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tienda.Vendedor'),
        ),
    ]
